---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by cherry.
--- DateTime: 2024/5/31 5:51 下午
---
if redis.call("get",KEYS[1])==ARGV[1] then
    return redis.call("del",KEYS[1])
else
    return 0
end

